[package]
name = "dragon_map"
version = "0.1.0"
authors = ["Martin Betak <matobet@gmail.com>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]
name = "dragon_map"

[dependencies]
redis-module = { version = "0.13", features = ["experimental-api"] }
itertools = "0.9"

[dev-dependencies]
rand = "0.7"
redis = "0.20"
redis-module = { version = "0.13", features = ["experimental-api", "test"] }
redis-test-macros = { path = "redis-test-macros" }
